[msvc][bug] Fix min/max after C-std... includes
One of stdarg.h, stdio.h, stdlib.h, or string.h (probably stdarg or
stdlib) being included breaks the MSVC build:

    error C2059: syntax error: '<parameter-list>'

Apply a dirty fix for now by defining min/max before the new includes,
so the CI is green again.