[ci] Install missing package uuid-dev to "Build on Ubuntu with GCC for Linux"
Symptom was:
> [..]/avs/uuid.cpp:6:10: fatal error: uuid/uuid.h: No such file or directory
>     6 | #include <uuid/uuid.h>
>       |          ^~~~~~~~~~~~~